### ISSUE TITLE
更新完so后，在读取成遇到崩溃

### ISSUE THREAD

**Issue by sarmy111** [noodle1983/UnityAndroidIl2cppPatchDemo#29]
at libil2cpp.0x18bbf78(Native Method)
	at libil2cpp.0x18b0468(Native Method)
	at libil2cpp.il2cpp_init(il2cpp_init:36)
	at libunity.0x5e7efc(Native Method)
	at libunity.0x654010(Native Method)
	at libunity.0x654bc8(Native Method)
	at libunity.0x6691f8(Native Method)
	at base.0x4276c(Native Method)
有人遇到过类似的问题吗

**Comment by noodle1983** [comment]
https://github.com/noodle1983/UnityAndroidIl2cppPatchDemo/wiki
